### ISSUE TITLE
Epic: Improve Pagination's UX for A11y

### ISSUE THREAD

**Issue by marvieqa** [CodeForPhilly/clean-and-green-philly#658]
## Description
This ticket describes the ideal behaviour of the pagination, for when we have the resources to update its current implementation. This would improve and resolve the overall accessibility of the pagination experience

## Requirements
- [ ] Properties displayed on a page should be wrapped in a `<list>`
- [ ] **Pagination should be links** that takes you to a page, not a button. (See [W3C Pagination example](https://design-system.w3.org/components/pagination.html)) Currently, it's a collection of `<buttons>`.
- [ ] Focus handling
  - If the Properties displayed are wrapped in a `<list>`
    - [ ] Manage focus to go to the property `<list>` when the new (next or previous) page loads, so users don't need to step backwards to get to the list; 
  -  If the properties displayed is not in a list, 
    - [ ] Add a visually-hidden text "Property List Page x"
    - [ ] Put the focus on this text when the new page load. This also assists screen reader user's understanding.
- [ ] Page numbers should have `<aria-current="page">` to denote the current selection.

## Additional notes
- This would eliminate the need for adding `aria-live` regions just to announce that a new set of properties has loaded as described in the following opened tickets.

#340 
#635
